[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#808080"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"
font = "sans serif"